# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sungju Kim
email: goddoe2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  AI Research Engineer.
  Excited with AI, Code LLM and NLP.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://goddoe.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username: goddoe

# Navigation
header_pages:
  - creative.md
  - about.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-jupyter-notebook

# pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude from processing.
exclude:
  - creative/what-lies-beyond/docs
  - creative/what-lies-beyond/.gitignore
  - creative/what-lies-beyond-2/docs
  - creative/what-lies-beyond-2/.gitignore
  - creative/what-lies-beyond-2/.mcp.json

